// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://oqvgpmpgsajbceuxrjuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdmdwpmpgsajbceuxrjuciwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2MjcxODMsImV4cCI6MjA5MjIwMzE4M30._rMkV9raZt634Qko8FbOWivvcmbWksn29eLORNDQqW4";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);